# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_pb2 as master__pb2


class MasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PartitionInput = channel.unary_unary(
                '/Master/PartitionInput',
                request_serializer=master__pb2.PartitionRequest.SerializeToString,
                response_deserializer=master__pb2.MapAndPartitionResponse.FromString,
                )
        self.GetPoints = channel.unary_unary(
                '/Master/GetPoints',
                request_serializer=master__pb2.GetPointByCentroidRequest.SerializeToString,
                response_deserializer=master__pb2.GetCentroidResponse.FromString,
                )


class MasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PartitionInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PartitionInput': grpc.unary_unary_rpc_method_handler(
                    servicer.PartitionInput,
                    request_deserializer=master__pb2.PartitionRequest.FromString,
                    response_serializer=master__pb2.MapAndPartitionResponse.SerializeToString,
            ),
            'GetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoints,
                    request_deserializer=master__pb2.GetPointByCentroidRequest.FromString,
                    response_serializer=master__pb2.GetCentroidResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Master(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PartitionInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/PartitionInput',
            master__pb2.PartitionRequest.SerializeToString,
            master__pb2.MapAndPartitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/GetPoints',
            master__pb2.GetPointByCentroidRequest.SerializeToString,
            master__pb2.GetCentroidResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
