# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\",\n\x05Point\x12\r\n\x05index\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"S\n\x10PartitionRequest\x12\x0f\n\x07indexes\x18\x01 \x03(\x05\x12\x19\n\tcentroids\x18\x02 \x03(\x0b\x32\x06.Point\x12\x13\n\x0bnumReducers\x18\x03 \x01(\x05\")\n\x17MapAndPartitionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"/\n\x19GetPointByCentroidRequest\x12\x12\n\ncentroidID\x18\x01 \x01(\x05\"-\n\x13GetCentroidResponse\x12\x16\n\x06points\x18\x01 \x03(\x0b\x32\x06.Point2\x86\x01\n\x06Master\x12=\n\x0ePartitionInput\x12\x11.PartitionRequest\x1a\x18.MapAndPartitionResponse\x12=\n\tGetPoints\x12\x1a.GetPointByCentroidRequest\x1a\x14.GetCentroidResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=16
  _globals['_POINT']._serialized_end=60
  _globals['_PARTITIONREQUEST']._serialized_start=62
  _globals['_PARTITIONREQUEST']._serialized_end=145
  _globals['_MAPANDPARTITIONRESPONSE']._serialized_start=147
  _globals['_MAPANDPARTITIONRESPONSE']._serialized_end=188
  _globals['_GETPOINTBYCENTROIDREQUEST']._serialized_start=190
  _globals['_GETPOINTBYCENTROIDREQUEST']._serialized_end=237
  _globals['_GETCENTROIDRESPONSE']._serialized_start=239
  _globals['_GETCENTROIDRESPONSE']._serialized_end=284
  _globals['_MASTER']._serialized_start=287
  _globals['_MASTER']._serialized_end=421
# @@protoc_insertion_point(module_scope)
